### ISSUE TITLE
How do I get the nth char of a string?

### ISSUE THREAD

**Issue by buren-trialbee** [jeorgun/Vivaldi#1]
Hi,
first of sweet that you created your own language :) (And in such a short time!) 

I'm playing around a bit with it and I'm trying to find a way to get the char at specified index of a string and  is there any way to do that? (perhaps I've missed something :))

thanks!

**Comment by buren** [comment]
```
let a = "asd"
>>> for i in a.start(): puts(i)
caught exception: "no such member: start"

>>> for i in a.end(): puts(i)
caught exception: "no such member: start"
```

**Comment by buren** [comment]
This works:
```
let string_itr = "asd".start()
while !string_itr.at_end(): do
  let i = string_itr.get()
  puts(i)
  string_itr.increment()
end
```

**Comment by buren-trialbee** [comment]
Closed https://github.com/jeorgun/Vivaldi/issues/1#issuecomment-74441753

**Comment by jeorgun** [comment]
Whoops— I guess I forgot the `at()` method. Just added it. Thanks for bringing it to my attention!

For iterating through each character of a string, just

    for i in "I am a string": puts(i)

should work (at least it does for me; if it doesn't, that's a bug). StringIterators don't, at the moment, act as ranges (i.e. they don't have a `start()` method), so they can't be called on for loops. Eventually it should be possible to do

    let str = "another string"
    for i in str.start() to str.end(): puts(i)

but StringIterator doesn't support the required methods at the moment.
